# Generated by Django 3.2.5 on 2021-07-22 18:49

from django.db import migrations
from django_celery_beat.models import PeriodicTask, IntervalSchedule

def create_chain_check_schedule(apps, schema_editor):
    schedule, _ = IntervalSchedule.objects.get_or_create(
        every=10,
        period=IntervalSchedule.SECONDS
    )

    PeriodicTask.objects.create(
        interval=schedule,
        name='Perform chain check',
        task='chainlinks.tasks.run_all_check_jobs'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('chainlinks', '0001_initial'),
        ('django_celery_beat', '0015_edit_solarschedule_events_choices')
    ]

    operations = [
        migrations.RunPython(create_chain_check_schedule)
    ]
