# Generated by Django 3.2.6 on 2021-09-23 13:09

from django.db import migrations
from django_celery_beat.models import PeriodicTask, IntervalSchedule


def create_chain_cleanup_schedule(apps, schema_editor):
    schedule, _ = IntervalSchedule.objects.get_or_create(
        every=12,
        period=IntervalSchedule.HOURS
    )

    PeriodicTask.objects.create(
        interval=schedule,
        name='Perform chain clean up',
        task='chainlinks.tasks.clean_all_check_jobs'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('chainlinks', '0003_alter_chainjob_blockchain_id'),
        ('django_celery_beat', '0015_edit_solarschedule_events_choices')
    ]

    operations = [
        migrations.RunPython(create_chain_cleanup_schedule)
    ]
