# Generated by Django 3.2.6 on 2021-10-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainlinks', '0004_auto_20210923_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='chainjob',
            name='visible',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
